// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm0Pf9ntYM9LCh0X_XYoiakk02ZJYN7qU',
    appId: '1:42978763789:web:73852ef906e523a064e144',
    messagingSenderId: '42978763789',
    projectId: 'pets-app-18f8e',
    authDomain: 'pets-app-18f8e.firebaseapp.com',
    storageBucket: 'pets-app-18f8e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDij_2oMwpMu_sDQUx1Gdyx9f6zjyehTuY',
    appId: '1:42978763789:android:149c6962c060da8d64e144',
    messagingSenderId: '42978763789',
    projectId: 'pets-app-18f8e',
    storageBucket: 'pets-app-18f8e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKVu3opuke-b6BDu4MqVWRORLnCOazpGw',
    appId: '1:42978763789:ios:6098ce944d08dbd664e144',
    messagingSenderId: '42978763789',
    projectId: 'pets-app-18f8e',
    storageBucket: 'pets-app-18f8e.appspot.com',
    iosBundleId: 'com.example.petsShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKVu3opuke-b6BDu4MqVWRORLnCOazpGw',
    appId: '1:42978763789:ios:e8e3fd7485a14e6264e144',
    messagingSenderId: '42978763789',
    projectId: 'pets-app-18f8e',
    storageBucket: 'pets-app-18f8e.appspot.com',
    iosBundleId: 'com.example.petsShop.RunnerTests',
  );
}
